name: General check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile

      # NX Cloud Task
      - name: NX Cloud Build (exclude examples)
        run: pnpm build
      - run: pnpm lint
